export const LARGE_ASTEROID_1 = 'LARGE_ASTEROID_1';
export const LARGE_ASTEROID_2 = 'LARGE_ASTEROID_2';
export const LARGE_ASTEROID_3 = 'LARGE_ASTEROID_3';
export type LARGE_ASTEROID = typeof LARGE_ASTEROID_1 | typeof LARGE_ASTEROID_2 | typeof LARGE_ASTEROID_3;

export const MEDIUM_ASTEROID_1 = 'MEDIUM_ASTEROID_1';
export const MEDIUM_ASTEROID_2 = 'MEDIUM_ASTEROID_2';
export const MEDIUM_ASTEROID_3 = 'MEDIUM_ASTEROID_3';
export type MEDIUM_ASTEROID = typeof MEDIUM_ASTEROID_1 | typeof MEDIUM_ASTEROID_2 | typeof MEDIUM_ASTEROID_3;

export const SMALL_ASTEROID_1 = 'SMALL_ASTEROID_1';
export const SMALL_ASTEROID_2 = 'SMALL_ASTEROID_2';
export type SMALL_ASTEROID = typeof SMALL_ASTEROID_1 | typeof SMALL_ASTEROID_2;

export type AsteroidType = LARGE_ASTEROID | MEDIUM_ASTEROID | SMALL_ASTEROID;
export default AsteroidType;